---@meta

---@class TNpcEntity
---@field declaredTrades?  TDeclaredTrade[]
---@field onEventUpdate?   fun(player: CBaseEntity, csid: integer, option: integer, npc: CBaseEntity)
---@field onEventFinish?   fun(player: CBaseEntity, csid: integer, option: integer, npc: CBaseEntity)
---@field onPath?          fun(npc: CBaseEntity)
---@field onPathComplete?  fun(npc: CBaseEntity)
---@field onPathPoint?     fun(npc: CBaseEntity)
---@field onSpawn?         fun(npc: CBaseEntity)
---@field onTimeTrigger?   fun(npc: CBaseEntity, triggerId: integer)
---@field onTrigger?       fun(player: CBaseEntity, npc: CBaseEntity): -1|nil
