# Keep CPM checkouts in one place across build directories, and notice when it moves.
if(NOT CPM_SOURCE_CACHE OR CPM_SOURCE_CACHE STREQUAL "OFF")
    if(DEFINED ENV{CPM_SOURCE_CACHE})
        set(cpm_cache "$ENV{CPM_SOURCE_CACHE}")
    else()
        set(cpm_cache "${CMAKE_SOURCE_DIR}/.cpm-cache")
    endif()
    set(CPM_SOURCE_CACHE "${cpm_cache}" CACHE PATH "Directory for cached CPM dependency sources" FORCE)
endif()
message(STATUS "CPM_SOURCE_CACHE: ${CPM_SOURCE_CACHE}")

if(CPM_SOURCE_CACHE AND DEFINED CPM_DIRECTORY)
    get_filename_component(cpm_expected_directory "${CPM_SOURCE_CACHE}/cpm" REALPATH)
    if(NOT "${CPM_DIRECTORY}" STREQUAL "${cpm_expected_directory}")
        message(STATUS "CPM source cache moved, clearing stale CPM_DIRECTORY")
        unset(CPM_DIRECTORY CACHE)
        unset(CPM_FILE CACHE)
    endif()
endif()
