# modules/init.txt lists what to build into xi_map: a directory of sources, a single .cpp, or a
# directory with its own CMakeLists.txt, which the caller includes once xi_map exists.
function(xi_collect_modules sources_var include_dirs_var cmakelists_var)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/modules/init.txt")

    set(sources "")
    set(include_dirs "")
    set(cmakelists "")
    file(STRINGS ${CMAKE_SOURCE_DIR}/modules/init.txt entries REGEX "^[^#\n].*")
    foreach(entry ${entries})
        set(module_path "${CMAKE_SOURCE_DIR}/modules/${entry}")
        if(IS_DIRECTORY "${module_path}")
            if(EXISTS "${module_path}/CMakeLists.txt")
                list(APPEND cmakelists "${module_path}/CMakeLists.txt")
                message(STATUS "Adding module CMakeLists.txt to build: ${module_path}/CMakeLists.txt")
                continue()
            endif()
            file(GLOB_RECURSE module_files "${module_path}/*.cpp" "${module_path}/*.h")
            list(APPEND include_dirs "${module_path}")
            list(APPEND sources ${module_files})
            message(STATUS "Adding module files to build: ${module_files}")
        elseif(entry MATCHES "\\.cpp$")
            list(APPEND sources "${module_path}")
            message(STATUS "Adding module files to build: ${module_path}")
        endif()
    endforeach()

    set(${sources_var} ${sources} PARENT_SCOPE)
    set(${include_dirs_var} ${include_dirs} PARENT_SCOPE)
    set(${cmakelists_var} ${cmakelists} PARENT_SCOPE)
endfunction()
