name: "build"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - base
      - everything

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Available machines:
# https://github.com/actions/runner-images/tree/main

jobs:
  Windows_64bit_Debug:
    runs-on: windows-2025
    steps:
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache 'build' folder
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-msvc64d
      - name: Configure CMake
        shell: bash
        run: |
          mkdir -p build
          cmake -S . -B build
      - name: Build
        shell: bash
        run: |
          cmake --build build -j4
      - name: Archive Executables
        uses: actions/upload-artifact@v4
        with:
          name: windows_executables
          path: |
            xi_connect.exe
            xi_map.exe
            xi_search.exe
            xi_world.exe

  Full_Startup_Checks_Windows:
    runs-on: windows-2025
    needs: Windows_64bit_Debug
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v4
        with:
          name: windows_executables
          path: .
      - uses: zach2good/setup-mariadb@v1
        with:
          database: xidb
      - name: Copy settings
        shell: bash
        run: |
          cp settings/default/* settings/
      - name: Install Python Dependencies
        shell: bash
        # TODO: Properly use python venv
        run: |
          python3 -m pip config set global.break-system-packages true
          python3 -m pip install -r tools/requirements.txt
      - name: Import SQL files
        shell: bash
        run: |
          python3 ./tools/dbtool.py setup
      - name: Startup checks
        shell: bash
        run: |
          python3 ./tools/ci/startup_checks.py